# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EkoGitHubUsers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'AFNetworking', '~> 3.0'
  # Pods for EkoGitHubUsers

  target 'EkoGitHubUsersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EkoGitHubUsersUITests' do
    # Pods for testing
  end

end
